### ISSUE TITLE
Reaver and Wash give a blank stdout with rtl8814au since version 1.6.4

### ISSUE THREAD

**Issue by kcdtv** [t6x/reaver-wps-fork-t6x#193]
I tried with the stable releases 1.6.1 - 1.6.2 and 1.6.3 and both reaver and wash work as they should.
With the latest commit they do not anymore.
With full verbose mode enabled reaver stays at "waiting for beacon" vs all targets
```
[+] Switching wlan1 to channel 6
[+] Waiting for beacon from B2:46:FCXXXXX
```
Wash does not show anything
Clearly something went wrong with this chip in the way to treat the beacons. 
I will pass by IRC this evening. Cheers.

**Comment by rofl0r** [comment]
the RTL8812AU driver from aircrack-ng is buggy, it produces wrong FCS checksum, but it says in the radiotap header: 1) FCS checksum bit is set 2) BAD_FCS checksum bit is not set.
@kimocoder  ^
as a quick fix, this could be fixed in the driver by always setting the BAD_FCS bit, but it would of course be better to debug where the bad checksum comes from.

**Comment by rofl0r** [comment]
oh it seems the issue is known, and a fix too https://github.com/aircrack-ng/rtl8812au/issues/28

**Comment by kimocoder** [comment]
It has been merged. Thanks for approving the fix.
