### ISSUE TITLE
How Unistall this version?

### ISSUE THREAD

**Issue by Veigalex** [t6x/reaver-wps-fork-t6x#278]
I don unistall this version.
Please help

apt-get unistal reaver not found...

**Comment by Veigalex** [comment]
I can not uninstall!
Please help me!

**Comment by Veigalex** [comment]
Please

**Comment by Asux30** [comment]
> I don unistall this version.
> Please help
> 
> apt-get unistal reaver not found...

apt-get **remove** reaver

**Comment by kcdtv** [comment]
For information `apt-get` is deprecated and `remove` does not uninstall the unnecessary dependencies.
And don't forget to get root privilege to execute the command  
`sudo apt autoremove reaver`
Saying so if you use the packet manager form your distribution it has nothing to do with our github repository, your issue is completely "off topic" here. 
Please check your distribution documentation and search the internet before opening issues, a 10 seconds search would have been enough to answer this question that you asked... more than 10 months ago...
