### ISSUE TITLE
I am guessing I am the issue! but please help!

### ISSUE THREAD

**Issue by CancunManny** [t6x/reaver-wps-fork-t6x#328]
So I had my laptop setup with unknown linux distro.  Might have been kali, might have been something else, but pretty sure it was lubuntu based.  The login screen, where we put in credentials wasn't on a floating screen, it was part of the full screen, and it was all the way to the left, on the middle of the screen (in case someone knows which distro I was using based on that).

I had pretty much opened all the networks around me.  Have a list of the PINs and the PWs.  Monday morning turned on the laptop, tested it, and was able to pretty much get into most of the networks around my house.  

Monday evening, went to friends house to use it there and my wireless card wasn't being recognized.  I tried re sitting the card, and no luck.  Came back home and couldn't get it to work.  Made the mistake to re install a new distro, heck I tried like 3 different ones, and the wireless card wouldn't get recognized.  At that point I figured it had to be a hardware issue.  Took card out, cleaned it, blew on the slot, put it back in, and it started working again.

Now I have a working laptop again.  However I tried with 4 different distros, and I am not able to crack any networks now.  I would find it very very odd that they "patched" the routers sometime between monday and tuesday of this week.  (I was able to crack em monday morning)

I was using wash to collect the APs info, then running this command to get the pin

sudo time reaver -i wlpxxx -b xx:4E:xx:49:xx:48 -K 1 -vvv

Know very little on how to use reaver, but seems the K means I am using pixiedust.  It seems there are different versions of pixiedust?  A bit confused, since it wouldn;t make sense to come up with a new list and take out stuff that was still working.

What can I post here to see if you guys can help me figure it out.

**Comment by kcdtv** [comment]
Hi! For testing and reporting an issue you need to have access to the router in order to be able to check and modify it configuration, 
If you can do so please open a new issue focusing on a precise device and problem. 
Your report need to include basic information such as:
  - OS and kernel version
  - Wifi device info
  - Full stdout with debugging option of reaver  (`-vvv`) and wash ( `-j` )

 I recommend you read our [troubleshooting guide](https://github.com/t6x/reaver-wps-fork-t6x/wiki/Troubleshooting)
